import = ["~/Documents/almk-dev/dot-files/home/alacritty-catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = -2

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = -3

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Alt"

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 4
y = 4

[window]
opacity = 0.80
blur = true
