[general]
import = ["/home/almk/.config/alacritty/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "JetBrains Mono"

[font]
size = 9

[font.offset]
x = 0
y = -3

[font.glyph_offset]
x = 0
y = -1

[window]
decorations = "none"
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 8
y = 8

[keyboard]
bindings = [
    { key = "N",      mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "Return", mods = "Alt",           action = "ToggleFullscreen" }
]
